# Generated by Django 3.0.5 on 2021-03-26 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200)),
                ('final_grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=30)),
                ('inc', models.CharField(max_length=30)),
                ('r_minus', models.CharField(max_length=30)),
                ('r_middle', models.CharField(max_length=30)),
                ('r_plus', models.CharField(max_length=30)),
                ('one_minus', models.CharField(max_length=30)),
                ('one_middle', models.CharField(max_length=30)),
                ('one_plus', models.CharField(max_length=30)),
                ('two_minus', models.CharField(max_length=30)),
                ('two_middle', models.CharField(max_length=30)),
                ('two_plus', models.CharField(max_length=30)),
                ('three_minus', models.CharField(max_length=30)),
                ('three_middle', models.CharField(max_length=30)),
                ('three_plus', models.CharField(max_length=30)),
                ('threepfourm', models.CharField(max_length=30)),
                ('four_minus', models.CharField(max_length=30)),
                ('fourmfourmid', models.CharField(max_length=30)),
                ('four_middle', models.CharField(max_length=30)),
                ('fourmfourp', models.CharField(max_length=30)),
                ('four_plus', models.CharField(max_length=30)),
                ('four_plusplus', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('semester', models.PositiveIntegerField()),
                ('grade', models.PositiveIntegerField()),
                ('class_name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_spending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('class_code', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
