# Generated by Django 3.0.5 on 2021-03-31 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_studentgrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='studentgrades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgrades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencerec',
            name='expectation',
            field=models.CharField(max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='four_middle',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='four_minus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='four_plus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='four_plusplus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='fourmfourmid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='fourmfourp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='inc',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='one_middle',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='one_minus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='one_plus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='r_middle',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='r_minus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='r_plus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='three_middle',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='three_minus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='three_plus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='threepfourm',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='two_middle',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='two_minus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='two_plus',
            field=models.CharField(max_length=10),
        ),
    ]
