# Generated by Django 3.0.5 on 2021-03-31 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20210331_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerec',
            name='studentgrades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentgrades', to='accounts.Studentgrades'),
        ),
        migrations.AddField(
            model_name='evidencerec',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_userevidence', to=settings.AUTH_USER_MODEL),
        ),
    ]
