# Generated by Django 3.0.5 on 2021-04-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210331_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencerec',
            name='four_middle',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='four_minus',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='four_plus',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='four_plusplus',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='fourmfourmid',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='fourmfourp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='inc',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='level',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='one_middle',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='one_minus',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='one_plus',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='r_middle',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='r_minus',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='r_plus',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='three_middle',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='three_minus',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='three_plus',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='threepfourm',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='two_middle',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='two_minus',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='two_plus',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
