# Generated by Django 3.0.5 on 2021-04-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210331_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencerec',
            name='user',
        ),
        migrations.AlterField(
            model_name='evidencerec',
            name='studentgrades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Studentgrades'),
        ),
    ]
