# Generated by Django 3.0.5 on 2021-04-06 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210405_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencerec',
            name='studentgrades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Studentgrades'),
        ),
    ]
