# Generated by Django 3.0.5 on 2021-04-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210405_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencerec',
            name='studentgrades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Studentgrades'),
        ),
    ]
