# Generated by Django 3.0.5 on 2021-04-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210406_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional',
            name='user',
        ),
        migrations.AddField(
            model_name='additional',
            name='studentgrades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Studentgrades'),
        ),
    ]
